In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

In [2]:
df=pd.read_csv('/kaggle/input/competitions/spaceship-titanic/train.csv')
test_df=pd.read_csv('/kaggle/input/competitions/spaceship-titanic/test.csv')

In [3]:
df.head()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True

In [4]:
df.shape

(8693, 14)

In [5]:
print(df['HomePlanet'].unique())

['Europa' 'Earth' 'Mars' nan]

In [6]:
df.isnull().mean()*100

PassengerId     0.000000
HomePlanet      2.312205
CryoSleep       2.496261
Cabin           2.289198
Destination     2.093639
Age             2.059128
VIP             2.335212
RoomService     2.082135
FoodCourt       2.105142
ShoppingMall    2.392730
Spa             2.105142
VRDeck          2.162660
Name            2.300702
Transported     0.000000
dtype: float64

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   8693 non-null   object
 1   HomePlanet    8492 non-null   object
 2   CryoSleep     8476 non-null   object
 3   Cabin         8494 non-null   object
 4   Destination   8511 non-null   object
 5   Age           8514 non-null   float64
 6   VIP           8490 non-null   object
 7   RoomService   8512 non-null   float64
 8   FoodCourt     8510 non-null   float64
 9   ShoppingMall  8485 non-null   float64
 10  Spa           8510 non-null   float64
 11  VRDeck        8505 non-null   float64
 12  Name          8493 non-null   object
 13  Transported   8693 non-null   bool
dtypes: bool(1), float64(6), object(7)
memory usage: 891.5+ KB

In [8]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['CryoSleep']=le.fit_transform(df['CryoSleep'])
test_df['CryoSleep']=le.fit_transform(test_df['CryoSleep'])

In [9]:
df['Total_Spending']=df['RoomService']+df['FoodCourt']+df['ShoppingMall']+df['Spa']+df['VRDeck']
test_df['Total_Spending']=test_df['RoomService']+test_df['FoodCourt']+test_df['ShoppingMall']+test_df['Spa']+test_df['VRDeck']

In [10]:
df['CryoSleep'] = np.where(df['Total_Spending'] > 0, 0, 1)

spending_cols = ['RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck'] 
df.loc[df['CryoSleep'] == True, spending_cols] = 0   
df['Total_Spending']=df['RoomService']+df['FoodCourt']+df['ShoppingMall']+df['Spa']+df['VRDeck']

In [11]:
test_df['CryoSleep'] = np.where(test_df['Total_Spending'] > 0, 0, 1)

spending_cols = ['RoomService', 'FoodCourt', 'ShoppingMall', 'Spa', 'VRDeck'] 
test_df.loc[test_df['CryoSleep'] == True, spending_cols] = 0   
test_df['Total_Spending']=test_df['RoomService']+test_df['FoodCourt']+test_df['ShoppingMall']+test_df['Spa']+test_df['VRDeck']

In [12]:
df.isnull().mean()*100

PassengerId       0.000000
HomePlanet        2.312205
CryoSleep         0.000000
Cabin             2.289198
Destination       2.093639
Age               2.059128
VIP               2.335212
RoomService       0.000000
FoodCourt         0.000000
ShoppingMall      0.000000
Spa               0.000000
VRDeck            0.000000
Name              2.300702
Transported       0.000000
Total_Spending    0.000000
dtype: float64

In [13]:
df['Age']=df['Age'].fillna(df['Age'].mean())
df['VIP']=df['VIP'].fillna(df['VIP'].mode())

In [14]:
test_df['Age']=test_df['Age'].fillna(test_df['Age'].mean())
test_df['VIP']=test_df['VIP'].fillna(test_df['VIP'].mode())

In [15]:
df['Surname'] = df['Name'].str.split().str[-1]
df.drop(columns=['Name'],axis=1,inplace=True)
test_df['Surname'] = test_df['Name'].str.split().str[-1]
test_df.drop(columns=['Name'],axis=1,inplace=True)
df.head()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Transported,Total_Spending,Surname
0,0001_01,Europa,1,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,False,0.0,Ofracculy
1,0002_01,Earth,0,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,True,736.0,Vines
2,0003_01,Europa,0,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,False,10383.0,Susent
3,0003_02,Europa,0,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,False,5176.0,Susent
4,0004_01,Earth,0,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,True,1091.0,Santantines

In [16]:
family_planet_map = df.groupby('Surname')['HomePlanet'].first()
df['HomePlanet'] = df['HomePlanet'].fillna(df['Surname'].map(family_planet_map))
df['HomePlanet'] = df['HomePlanet'].fillna(df['HomePlanet'].mode()[0])

family_planet_map = test_df.groupby('Surname')['HomePlanet'].first()
test_df['HomePlanet'] = test_df['HomePlanet'].fillna(test_df['Surname'].map(family_planet_map))
test_df['HomePlanet'] = test_df['HomePlanet'].fillna(test_df['HomePlanet'].mode()[0])

In [17]:
df.drop(columns=['Surname'],axis=1,inplace=True)

test_df.drop(columns=['Surname'],axis=1,inplace=True)

In [18]:
df.isnull().sum()

PassengerId         0
HomePlanet          0
CryoSleep           0
Cabin             199
Destination       182
Age                 0
VIP               203
RoomService         0
FoodCourt           0
ShoppingMall        0
Spa                 0
VRDeck              0
Transported         0
Total_Spending      0
dtype: int64

In [19]:
print(df['Destination'].unique())
print(df['HomePlanet'].unique())

['TRAPPIST-1e' 'PSO J318.5-22' '55 Cancri e' nan]
['Europa' 'Earth' 'Mars']

In [20]:
df['HomePlanet']=le.fit_transform(df['HomePlanet'])
df['Destination']=le.fit_transform(df['Destination'])
df['VIP']=le.fit_transform(df['VIP'])
df['Transported']=le.fit_transform(df['Transported'])

test_df['HomePlanet'] = le.fit_transform(test_df['HomePlanet'])
test_df['Destination'] = le.fit_transform(test_df['Destination'])
test_df['VIP'] = le.fit_transform(test_df['VIP'])

In [21]:
df['Cabin'].nunique()

6560

In [22]:
df['Cabin'] = df['Cabin'].fillna('U/0/U')
df[['Cabin_Deck', 'Cabin_Num', 'Cabin_Side']] = df['Cabin'].str.split('/', expand=True)

test_df['Cabin'] = test_df['Cabin'].fillna('U/0/U')
test_df[['Cabin_Deck', 'Cabin_Num', 'Cabin_Side']] = test_df['Cabin'].str.split('/', expand=True)
print("Decks:", df['Cabin_Deck'].unique())
print("Sides:", df['Cabin_Side'].unique())

Decks: ['B' 'F' 'A' 'G' 'U' 'E' 'D' 'C' 'T']
Sides: ['P' 'S' 'U']

In [23]:
df['Cabin_Side']=le.fit_transform(df['Cabin_Side'])

deck_order = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'T']
from sklearn.preprocessing import OrdinalEncoder
oe=OrdinalEncoder(categories=[deck_order],handle_unknown='use_encoded_value', unknown_value=-1)
df[['Cabin_Deck']] = oe.fit_transform(df[['Cabin_Deck']])

test_df['Cabin_Side']=le.fit_transform(test_df['Cabin_Side'])
test_df[['Cabin_Deck']] = oe.fit_transform(test_df[['Cabin_Deck']])

In [24]:
test_df.head()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Total_Spending,Cabin_Deck,Cabin_Num,Cabin_Side
0,0013_01,0,1,G/3/S,2,27.0,0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,3,1
1,0018_01,0,0,F/4/S,2,19.0,0,0.0,9.0,0.0,2823.0,0.0,2832.0,5.0,4,1
2,0019_01,1,1,C/0/S,0,31.0,0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0,1
3,0021_01,1,0,C/1/S,2,38.0,0,0.0,6652.0,0.0,181.0,585.0,7418.0,2.0,1,1
4,0023_01,0,0,F/5/S,2,20.0,0,10.0,0.0,635.0,0.0,0.0,645.0,5.0,5,1

In [25]:
df.drop(columns=['Cabin'],axis=1,inplace=True)
df['Cabin_Num'] = pd.to_numeric(df['Cabin_Num'], errors='coerce')

test_df.drop(columns=['Cabin'],axis=1,inplace=True)
test_df['Cabin_Num'] = pd.to_numeric(test_df['Cabin_Num'], errors='coerce')

In [26]:
df['Group_Id'] = df['PassengerId'].str.split('_').str[0].astype(int)
df['Group_Size_Pos'] = df['PassengerId'].str.split('_').str[1].astype(int)
df["GroupSize"] = df.groupby("Group_Id")["PassengerId"].transform("count")
df["IsAlone"]   = (df["GroupSize"] == 1).astype(int)
df.drop('PassengerId', axis=1, inplace=True)

test_df['Group_Id'] = test_df['PassengerId'].str.split('_').str[0].astype(int)
test_df['Group_Size_Pos'] = test_df['PassengerId'].str.split('_').str[1].astype(int)
test_df["GroupSize"] = test_df.groupby("Group_Id")["PassengerId"].transform("count")
test_df["IsAlone"] = (test_df["GroupSize"] == 1).astype(int)

In [27]:
df['is_child']=np.where(df['Age']<13,1,0)
df['is_teen']=np.where((df['Age']>=13) & (df['Age']<19),1,0)
df['is_adult']=np.where((df['Age']>=19) & (df['Age']<60),1,0)
df['is_senior']=np.where(df['Age']>=60,1,0)

test_df['is_child'] = np.where(test_df['Age'] < 13, 1, 0)
test_df['is_teen'] = np.where((test_df['Age'] >= 13) & (test_df['Age'] < 19), 1, 0)
test_df['is_adult'] = np.where((test_df['Age'] >= 19) & (test_df['Age'] < 60), 1, 0)
test_df['is_senior'] = np.where(test_df['Age'] >= 60, 1, 0)

In [28]:
df.head()

,HomePlanet,CryoSleep,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,...,Cabin_Num,Cabin_Side,Group_Id,Group_Size_Pos,GroupSize,IsAlone,is_child,is_teen,is_adult,is_senior
0,1,1,2,39.0,0,0.0,0.0,0.0,0.0,0.0,...,0,0,1,1,1,1,0,0,1,0
1,0,0,2,24.0,0,109.0,9.0,25.0,549.0,44.0,...,0,1,2,1,1,1,0,0,1,0
2,1,0,2,58.0,1,43.0,3576.0,0.0,6715.0,49.0,...,0,1,3,1,2,0,0,0,1,0
3,1,0,2,33.0,0,0.0,1283.0,371.0,3329.0,193.0,...,0,1,3,2,2,0,0,0,1,0
4,0,0,2,16.0,0,303.0,70.0,151.0,565.0,2.0,...,1,1,4,1,1,1,0,1,0,0

In [29]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from xgboost import XGBClassifier
x=df.drop('Transported',axis=1)
y=df['Transported']
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
model = XGBClassifier(
    n_estimators=1000,
    learning_rate=0.01,
    max_depth=6,
    subsample=0.8,
    colsample_bytree=0.8,
    tree_method='hist', 
    device='gpu',      
    random_state=42
)
model.fit(x_train, y_train)
y_pred=model.predict(x_test)
accuracy_score(y_test,y_pred)

/usr/local/lib/python3.12/dist-packages/xgboost/core.py:751: UserWarning: [21:21:10] WARNING: /__w/xgboost/xgboost/src/common/error_msg.cc:62: Falling back to prediction using DMatrix due to mismatched devices. This might lead to higher memory usage and slower performance. XGBoost is running on: cuda:0, while the input data is on: cpu.
Potential solutions:
- Use a data structure that matches the device ordinal in the booster.
- Set the device for booster before call to inplace_predict.

This warning will only be shown once.

  return func(**kwargs)

0.7826336975273146

In [30]:


# 1. Pehle PassengerId ko kahin save kar lo submission ke liye
test_ids = test_df['PassengerId'].copy()

# 2. Ab test_df se PassengerId aur koi bhi bacha hua 'object' column drop karo
# Hum wahi columns use karenge jo training ke 'x' mein hain
test_df_numeric = test_df[x.columns] 

# 3. Ab predict karo (Ab error nahi aayega)
y_pred = model.predict(test_df_numeric)

# 4. Labels convert karo (True/False ya original labels mein)
final_labels = le.inverse_transform(y_pred)

# Ensure karein ki final_labels 'True'/'False' strings ya boolean hain
final_labels = [bool(i) for i in final_labels]

# 3. DataFrame banayein sahi names ke saath
submission = pd.DataFrame({
    'PassengerId': test_ids, # Original IDs from test.csv
    'Transported': final_labels
})

# 4. Save karein
submission.to_csv('submission.csv', index=False)

print("Check clear: Column names are", submission.columns.tolist())
print("Check clear: First 5 labels are", submission['Transported'].head().tolist())

submission.to_csv('submission.csv', index=False)
print("Submission file ready!")

Check clear: Column names are ['PassengerId', 'Transported']
Check clear: First 5 labels are [True, True, True, True, True]
Submission file ready!

In [31]:
submission.head()

  PassengerId  Transported
0     0013_01         True
1     0018_01         True
2     0019_01         True
3     0021_01         True
4     0023_01         True